apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.cluster_name }}-hook
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: "huszty/etcd_healthchecker:latest"
        args: ["/main", "bootstrap"]
        env:
        - name: ETCD_ENDPOINT
          value: {{ .Values.cluster_name }}:2379
