apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.cluster_name }}-app
  labels:
    app: demo
spec:
  containers:
  - name: demo
    image: "huszty/etcd_healthchecker:latest"
    env:
    - name: ETCD_ENDPOINT
      value: {{ .Values.cluster_name }}:2379
